function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function br(d){if(!d)return'';let [y,m,day]=d.split('-');return `${day}/${m}/${y}`}
function link(u,label){return u?`<a class="btn" target="_blank" rel="noopener" href="${esc(u)}">${label}</a>`:''}
function links(arr,legacy,label){const a=[...new Set([...(Array.isArray(arr)?arr:[]),legacy].filter(Boolean))];return a.map((u,i)=>link(u,a.length>1?`${label} ${i+1}`:label)).join('')}
function photoDelivery(x){if(x.rawPhotosDelivery==='all')return'Entrega de todas as fotos não tratadas/originais';if(x.rawPhotosDelivery==='none')return'Fotos não tratadas/originais não incluídas';if(x.rawPhotosDelivery==='custom')return x.rawPhotosCustom||'Condição personalizada';return x.rawPhotosCustom||''}
function photoDeadline(x){if(x.deliveryDays==='custom')return x.deliveryCustom||'Personalizado';return x.deliveryDays?`${x.deliveryDays} dias`:x.deliveryCustom||''}
function item(x,i){
 let isPhoto=x.format==='Sessão de fotos';
 let body=isPhoto?`<div class="block"><b>Fotografia profissional</b><p>${x.photoHours?`Duração da sessão: ${esc(x.photoHours)}h\n`:''}${x.treatedPhotos?`Fotos tratadas: ${esc(x.treatedPhotos)}\n`:''}${photoDelivery(x)?`Fotos não tratadas/originais: ${esc(photoDelivery(x))}\n`:''}${photoDeadline(x)?`Prazo de entrega: ${esc(photoDeadline(x))}`:''}</p></div>${x.photoObjective?`<div class="block"><b>Objetivo da sessão</b><p>${esc(x.photoObjective)}</p></div>`:''}${x.photoLocation?`<div class="block"><b>Local</b><p>${esc(x.photoLocation)}</p></div>`:''}${x.photoNotes?`<div class="block"><b>Referências / orientações</b><p>${esc(x.photoNotes)}</p></div>`:''}`:
 x.format==='Carrossel'?`<div class="block"><b>Cards${x.cardCount?' • '+x.cardCount:''}</b><p>${esc(x.cards)}</p></div>`:
 x.format==='Estático'?`<div class="block"><b>Texto da arte</b><p>${esc(x.artText)}</p></div><div class="block"><b>Direção visual</b><p>${esc(x.artDirection)}</p></div>`:
 `<div class="block"><b>Cenas / falas / takes</b><p>${esc(x.scenes)}</p></div>`;
 return `<section class="card"><div class="content-head"><div><span class="pill">Conteúdo ${i+1}</span><span class="pill">${esc(x.format)}</span>${x.status?`<span class="pill">${esc(x.status)}</span>`:''}<h2>${esc(x.title||`Conteúdo ${i+1}`)}</h2></div>${x.captureDate?`<span class="pill">${isPhoto?'Sessão':'Captação'} ${br(x.captureDate)}</span>`:''}</div>${x.briefing?`<div class="block"><b>Briefing</b><p>${esc(x.briefing)}</p></div>`:''}${x.imageLink?`<div class="block"><b>Imagem / foto de referência</b><img class="ref" src="${esc(x.imageLink)}" onerror="this.style.display='none'"><div class="actions">${link(x.imageLink,'Abrir imagem')}</div></div>`:''}${!isPhoto&&x.goal?`<div class="block"><b>Objetivo</b><p>${esc(x.goal)}</p></div>`:''}${!isPhoto&&x.hook?`<div class="block"><b>Gancho</b><p>${esc(x.hook)}</p></div>`:''}${body}${!isPhoto&&x.cta?`<div class="block"><b>CTA</b><p>${esc(x.cta)}</p></div>`:''}<div class="actions">${links(x.referenceLinks,x.referenceLink,'Abrir referência')}${links(x.driveLinks,x.approvalLink,'Abrir material no Drive')}</div></section>`;
}
function decodeFirestore(v){if(v==null)return null;if('stringValue'in v)return v.stringValue;if('integerValue'in v)return Number(v.integerValue);if('doubleValue'in v)return Number(v.doubleValue);if('booleanValue'in v)return v.booleanValue;if('nullValue'in v)return null;if('arrayValue'in v)return (v.arrayValue.values||[]).map(decodeFirestore);if('mapValue'in v){let o={};for(const[k,val]of Object.entries(v.mapValue.fields||{}))o[k]=decodeFirestore(val);return o}return null}
async function load(){
 const token=new URLSearchParams(location.search).get('p');if(!token)throw new Error('missing');
 const docId='script_'+token.replace(/[^a-zA-Z0-9_-]/g,'');
 const url=`https://firestore.googleapis.com/v1/projects/humaniza-os/databases/(default)/documents/publicQuotes/${encodeURIComponent(docId)}?key=AIzaSyB2xU6wgDjswece50JVE-thiCb40wP-58M`;
 const r=await fetch(url);if(!r.ok)throw new Error('not found');const raw=await r.json(),p={};for(const[k,v]of Object.entries(raw.fields||{}))p[k]=decodeFirestore(v);
 const items=p.items||[],dates=p.captureDates||[...new Set(items.map(x=>x.captureDate).filter(Boolean))];
 document.getElementById('app').innerHTML=`<section class="hero"><span class="pill">Projeto de conteúdo</span><h1>${esc(p.client||'Projeto Humaniza')}</h1><p class="muted">Roteiros, briefing, referências e materiais preparados pela Humaniza para este projeto.</p></section><section class="summary"><div><small>Conteúdos</small><strong>${items.length}</strong></div><div><small>Período</small><strong>${esc(p.period||'Projeto avulso')}</strong></div><div><small>Captação</small><strong>${dates.length?dates.map(br).join(' • '):'A definir'}</strong></div></section><h2 class="section-title">Conteúdos do projeto</h2>${items.map(item).join('')}`;
}
load().catch(()=>document.getElementById('app').innerHTML='<section class="hero"><h1>Link inválido ou expirado</h1><p class="muted">Solicite um novo link à equipe Humaniza.</p></section>');
