const {onCall,HttpsError}=require("firebase-functions/v2/https");
const {initializeApp}=require("firebase-admin/app");
const {getAuth}=require("firebase-admin/auth");
const {getFirestore,FieldValue}=require("firebase-admin/firestore");
initializeApp();
const ADMIN_EMAIL="agenciahumanizamedia@gmail.com";
const db=getFirestore();
function admin(request){if(!request.auth||String(request.auth.token.email||"").toLowerCase()!==ADMIN_EMAIL)throw new HttpsError("permission-denied","Somente o administrador pode realizar esta ação.")}
function token(){const crypto=require('crypto');return crypto.randomBytes(24).toString('hex')}
exports.createAgencyUser=onCall({region:"us-central1"},async(request)=>{admin(request);const {email,password,displayName,role,recordId}=request.data||{};const normalizedEmail=String(email||"").trim().toLowerCase();if(!normalizedEmail||!password||!displayName||!recordId||!["client","team"].includes(role))throw new HttpsError("invalid-argument","Dados incompletos.");if(String(password).length<8)throw new HttpsError("invalid-argument","Senha mínima: 8 caracteres.");let user;try{user=await getAuth().createUser({email:normalizedEmail,password:String(password),displayName:String(displayName)})}catch(e){if(e.code==="auth/email-already-exists")throw new HttpsError("already-exists","Este e-mail já possui acesso.");throw new HttpsError("internal",e.message||"Falha ao criar usuário.")}await db.doc(`access/${user.uid}`).set({uid:user.uid,email:normalizedEmail,displayName:String(displayName),role,recordId:String(recordId),active:true,createdAt:FieldValue.serverTimestamp(),createdByUid:request.auth.uid});const col=role==="client"?"clients":"team";await db.doc(`${col}/${recordId}`).set({authUid:user.uid,accessRole:role,accessActive:true,updatedAt:FieldValue.serverTimestamp()},{merge:true});return{ok:true,uid:user.uid,email:normalizedEmail,role}});
exports.saveQuote=onCall({region:"us-central1"},async(request)=>{admin(request);const d=request.data||{};
if(d.settingsOnly){const s=d.settings||{};await db.doc('quoteSettings/main').set({businessName:String(s.businessName||'Agência Humaniza'),defaultVideoPrice:Math.max(0,Number(s.defaultVideoPrice||0)),defaultPhotoPrice:Math.max(0,Number(s.defaultPhotoPrice||0)),comboDiscount:Math.min(100,Math.max(0,Number(s.comboDiscount||0))),discountExplanation:String(s.discountExplanation||''),tiers:Array.isArray(s.tiers)?s.tiers.map(t=>({qty:Math.max(0,Number(t.qty||0)),pct:Math.min(100,Math.max(0,Number(t.pct||0)))})):[],updatedAt:FieldValue.serverTimestamp(),updatedBy:request.auth.uid},{merge:true});return{ok:true}}
if(!String(d.prospectName||'').trim())throw new HttpsError('invalid-argument','Nome do prospect é obrigatório.');
const service=['Vídeo','Foto','Vídeo + Foto'].includes(String(d.service))?String(d.service):'Vídeo';
let ref=d.id?db.doc(`quotes/${d.id}`):db.collection('quotes').doc();let old=(await ref.get()).data()||{};const publicToken=old.publicToken||token();
const vq=(service==='Vídeo'||service==='Vídeo + Foto')?Math.max(0,Number(d.videoQuantity||0)):0,vu=Math.max(0,Number(d.videoUnitPrice||0)),pq=(service==='Foto'||service==='Vídeo + Foto')?Math.max(0,Number(d.photoQuantity||0)):0,pu=Math.max(0,Number(d.photoUnitPrice||0));
const extras=Array.isArray(d.extras)?d.extras.map(x=>({name:String(x.name||''),value:Math.max(0,Number(x.value||0))})):[];const settings=(await db.doc('quoteSettings/main').get()).data()||{};const tiers=Array.isArray(settings.tiers)?settings.tiers:[];const totalQty=vq+pq;const auto=tiers.filter(t=>Number(t.qty)<=totalQty).sort((a,b)=>Number(b.qty)-Number(a.qty))[0]?.pct||0;const pct=d.manualDiscount===null||d.manualDiscount===undefined?Number(auto):Math.min(100,Math.max(0,Number(d.manualDiscount||0)));
const videoBase=vq*vu,photoBase=pq*pu,base=videoBase+photoBase,extrasTotal=extras.reduce((a,x)=>a+x.value,0),discountAmount=base*pct/100,comboDiscountPct=service==='Vídeo + Foto'?Math.min(100,Math.max(0,Number(settings.comboDiscount||0))):0,comboDiscountAmount=(base-discountAmount)*comboDiscountPct/100,total=base-discountAmount-comboDiscountAmount+extrasTotal;
const data={prospectName:String(d.prospectName).trim(),email:String(d.email||'').trim(),whatsapp:String(d.whatsapp||'').trim(),segment:String(d.segment||'').trim(),objective:String(d.objective||'').trim(),macro:String(d.macro||'').trim(),service,videoQuantity:vq,videoUnitPrice:vu,photoQuantity:pq,photoUnitPrice:pu,extras,manualDiscount:d.manualDiscount===null||d.manualDiscount===undefined?null:Number(d.manualDiscount),discountPct:pct,comboDiscountPct,subtotal:base+extrasTotal,discountAmount:discountAmount+comboDiscountAmount,total,discountExplanation:String(d.discountExplanation||settings.discountExplanation||''),validity:String(d.validity||''),deliverables:String(d.deliverables||''),notes:String(d.notes||''),businessName:String(settings.businessName||'Agência Humaniza'),publicToken,status:old.status||'sent',updatedAt:FieldValue.serverTimestamp(),updatedBy:request.auth.uid};if(!old.createdAt)data.createdAt=FieldValue.serverTimestamp();await ref.set(data,{merge:true});return{ok:true,id:ref.id,publicToken,total}});
exports.listQuotes=onCall({region:"us-central1"},async(request)=>{admin(request);const [qs,ss]=await Promise.all([db.collection('quotes').orderBy('createdAt','desc').limit(200).get(),db.doc('quoteSettings/main').get()]);return{quotes:qs.docs.map(x=>({id:x.id,...x.data(),createdAt:null,updatedAt:null,approvedAt:null,declinedAt:null})),settings:ss.exists?ss.data():{businessName:'Agência Humaniza',defaultVideoPrice:0,defaultPhotoPrice:0,comboDiscount:0,tiers:[],discountExplanation:''}}});
exports.getPublicQuote=onCall({region:"us-central1",cors:true},async(request)=>{const t=String(request.data?.token||'');if(t.length<20)throw new HttpsError('not-found','Proposta não encontrada.');const snap=await db.collection('quotes').where('publicToken','==',t).limit(1).get();if(snap.empty)throw new HttpsError('not-found','Proposta não encontrada.');const q=snap.docs[0].data();return{quote:{prospectName:q.prospectName||'',segment:q.segment||'',objective:q.objective||'',macro:q.macro||'',service:q.service||'',videoQuantity:q.videoQuantity||0,photoQuantity:q.photoQuantity||0,deliverables:q.deliverables||'',subtotal:q.subtotal||0,discountPct:q.discountPct||0,comboDiscountPct:q.comboDiscountPct||0,discountAmount:q.discountAmount||0,total:q.total||0,discountExplanation:q.discountExplanation||'',validity:q.validity||'',notes:q.notes||'',businessName:q.businessName||'Agência Humaniza',status:q.status||'sent'}}});
exports.respondToQuote=onCall({region:"us-central1",cors:true},async(request)=>{const t=String(request.data?.token||''),action=String(request.data?.action||'');if(!['approved','declined'].includes(action))throw new HttpsError('invalid-argument','Resposta inválida.');const snap=await db.collection('quotes').where('publicToken','==',t).limit(1).get();if(snap.empty)throw new HttpsError('not-found','Proposta não encontrada.');const ref=snap.docs[0].ref;await ref.set({status:action,[action==='approved'?'approvedAt':'declinedAt']:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()},{merge:true});return{ok:true,status:action}});
