import{initializeApp}from"https://www.gstatic.com/firebasejs/12.13.0/firebase-app.js";import{getFirestore,doc,getDoc,setDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.13.0/firebase-firestore.js";
const firebaseConfig={
  apiKey: "AIzaSyB2xU6wgDjswece50JVE-thiCb40wP-58M",
  authDomain: "humaniza-os.firebaseapp.com",
  projectId: "humaniza-os",
  storageBucket: "humaniza-os.firebasestorage.app",
  messagingSenderId: "416592042651",
  appId: "1:416592042651:web:66dd16c8e823e57d5b443e",
  measurementId: "G-YQMK274JER"
};const db=getFirestore(initializeApp(firebaseConfig));const token=new URLSearchParams(location.search).get('p');let data=null;let custom=[];
const ids=['responsible','email','company','cnpj','history','offer','audience','marketingGoal','important','production','contentIntent','mainMessage','references'];const el=id=>document.getElementById(id);
function renderCustom(){custom=(data.customQuestions||[]).map(x=>({...x}));if(!custom.length)return;el('customWrap').classList.remove('hide');el('customQuestions').innerHTML=custom.map((x,i)=>`<div class="custom"><label>${x.question||'Pergunta'}</label><textarea data-custom="${i}" placeholder="Sua resposta">${x.answer||''}</textarea></div>`).join('')}
async function init(){if(!token)return fail();try{const s=await getDoc(doc(db,'publicBriefings',token));if(!s.exists())return fail();data=s.data();el('loading').classList.add('hide');el('form').classList.remove('hide');el('projectName').textContent=data.clientName?('Briefing • '+data.clientName):'Briefing do projeto';const a=data.answers||{};ids.forEach(k=>{if(el(k))el(k).value=a[k]||''});if(data.clientType==='avulso'){el('agencyFields').classList.add('hide');el('avulsoFields').classList.remove('hide');el('audience2').value=a.audience||'';el('important2').value=a.important||''}renderCustom()}catch(e){fail()}}
function fail(){el('loading').textContent='Este briefing não está disponível. Peça um novo link à Humaniza.'}
el('send').onclick=async()=>{const av=data.clientType==='avulso';const answers={responsible:el('responsible').value.trim(),email:el('email').value.trim(),company:el('company').value.trim(),cnpj:el('cnpj').value.trim(),history:av?'':el('history').value.trim(),offer:av?'':el('offer').value.trim(),audience:(av?el('audience2'):el('audience')).value.trim(),marketingGoal:av?'':el('marketingGoal').value,important:(av?el('important2'):el('important')).value.trim(),production:av?el('production').value.trim():'',contentIntent:av?el('contentIntent').value.trim():'',mainMessage:av?el('mainMessage').value.trim():'',references:av?el('references').value.trim():''};document.querySelectorAll('[data-custom]').forEach(t=>{const i=+t.dataset.custom;if(custom[i])custom[i].answer=t.value.trim()});el('send').disabled=true;el('send').textContent='Enviando...';try{await setDoc(doc(db,'publicBriefings',token),{answers,customQuestions:custom,status:'completed',submittedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});el('form').classList.add('hide');el('done').classList.remove('hide')}catch(e){el('send').disabled=false;el('send').textContent='Enviar briefing para a Humaniza';alert('Não foi possível enviar agora. Tente novamente.')}};init();
